AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: >-
  AWS Lambda function to notify codedeploy events to slack
Parameters:
  SNSTopicArn:
    Type: String
  KeyIdParameter:
    Type: String
  slackChannelParameter:
    Type: String
  kmsEncryptedHookUrlParameter:
    Type: String
Resources:
  CodeDeployNotification:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: >-
        An Amazon SNS trigger that sends CodeDeploy events to Slack.
      MemorySize: 128
      Timeout: 10
      Events:
        CodeDeployNotification:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopicArn
      Policies:
        - KMSDecryptPolicy:
            KeyId: !Ref KeyIdParameter
      Environment:
        Variables:
          kmsEncryptedHookUrl: !Ref kmsEncryptedHookUrlParameter
          slackChannel: !Ref slackChannelParameter
